ROLE_MATRIX = {
    "Modérateur Test": {
        "ban": True,
        "unban": False,
        # "mute": True,
        # "unmute": True,
        "warn": True,
        "note": True,
        "clear": False,
    },
    "Modérateur": {
        "ban": True,
        "unban": False,
        # "mute": True,
        # "unmute": True,
        "warn": True,
        "note": True,
        "clear": False,
    },
    "Modérateur +": {
        "ban": True,
        "unban": False,
        # "mute": True,
        # "unmute": True,
        "warn": True,
        "note": True,
        "clear": False,
    },
    "Responsable Staff": {
        "ban": True,
        "unban": True,
        # "mute": True,
        # "unmute": True,
        "warn": True,
        "note": True,
        "clear": True,
    },
    "Admin": {
        "ban": True,
        "unban": True,
        # "mute": True,
        # "unmute": True,
        "warn": True,
        "note": True,
        "clear": True,
    },
}
